# Helm chart linting configuration for ct (chart-testing)

rules:
  # Disable rules that are not applicable for our use case
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1
  comments:
    min-spaces-from-content: 1
  comments-indentation: {}
  document-end: disable
  document-start: disable
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1
  empty-values: disable
  hyphens:
    max-spaces-after: 1
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
  key-duplicates: {}
  key-ordering: disable
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  new-line-at-end-of-file: {}
  octal-values: disable
  quoted-strings: disable
  trailing-spaces: {}
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']

# Allow longer lines for Kubernetes manifests
extends: default