# golangci-lint configuration for O-RAN Near-RT RIC
# This configuration is optimized for Go 1.21 compatibility with Go 1.17 codebase

run:
  timeout: 10m
  go: "1.21"
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

linters-settings:
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment  # Too strict for existing codebase
  gocyclo:
    min-complexity: 15
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/kubernetes/dashboard
  golint:
    min-confidence: 0.8
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  unused:
    go: "1.21"
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  funlen:
    lines: 100
    statements: 50
  gocognit:
    min-complexity: 20
  nestif:
    min-complexity: 4
  lll:
    line-length: 120
  maligned:
    suggest-new: true
  dupl:
    threshold: 100

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - asciicheck
    - gocognit
    - godot
    - godox
    - goerr113
    - nestif
    - prealloc
    - testpackage
    - wsl
  
  disable:
    - maligned  # Deprecated
    - scopelint # Deprecated, replaced by exportloopref
    - golint    # Deprecated, replaced by stylecheck

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - goconst
        - gocognit
        - scopelint
        - lll
    
    # Exclude some linters from running on generated files
    - path: ".*\\.pb\\.go"
      linters:
        - lll
        - errcheck
    
    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"
    
    # Exclude some gocritic messages
    - linters:
        - gocritic
      text: "unnecessaryDefer:"
  
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  # List of regexps of issue texts to exclude, empty list by default
  exclude:
    - 'declaration of "(err|ctx)" shadows declaration at'
    - 'should have a package comment'
    - 'comment on exported .* should be of the form'
    - 'at least one file in a package should have a package comment'

severity:
  default-severity: error
  case-sensitive: false