# Prometheus configuration for O-RAN Near-RT RIC Platform
# This configuration defines scraping targets for all platform components

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'oran-nearrt-ric'
    replica: 'prometheus-1'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules and alerts
rule_files:
  - "alerts/*.yml"
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 30s

  # Kubernetes API Server
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - role: endpoints
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https

  # Kubernetes Nodes
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics

  # Kubernetes Pods
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

  # Main Dashboard (Kubernetes Dashboard + O-RAN extensions)
  - job_name: 'main-dashboard'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - kubernetes-dashboard
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
        action: keep
        regex: kubernetes-dashboard
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
    metrics_path: /metrics
    scrape_interval: 30s

  # xApp Dashboard
  - job_name: 'xapp-dashboard'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - xapp-dashboard
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
        action: keep
        regex: xapp-dashboard
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
    metrics_path: /metrics
    scrape_interval: 30s

  # Federated Learning Coordinator
  - job_name: 'fl-coordinator'
    static_configs:
      - targets: ['fl-coordinator:8080']
    metrics_path: /fl/metrics
    scrape_interval: 30s

  # E2 Simulator
  - job_name: 'e2-simulator'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - oran-nearrt-ric
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
        action: keep
        regex: e2-interface
    metrics_path: /metrics
    scrape_interval: 15s  # Higher frequency for E2 latency monitoring

  # E2 Termination
  - job_name: 'e2-termination'
    static_configs:
      - targets: ['e2-termination:38001']
    metrics_path: /metrics
    scrape_interval: 15s

  # O-CU Simulator
  - job_name: 'o-cu-simulator'
    static_configs:
      - targets: ['o-cu-simulator:8080']
    metrics_path: /metrics
    scrape_interval: 30s

  # O-DU Simulator
  - job_name: 'o-du-simulator'
    static_configs:
      - targets: ['o-du-simulator:8080']
    metrics_path: /metrics
    scrape_interval: 30s

  # O-RU Simulator
  - job_name: 'o-ru-simulator'
    static_configs:
      - targets: ['o-ru-simulator:8080']
    metrics_path: /metrics
    scrape_interval: 30s

  # A1 Mediator
  - job_name: 'a1-mediator'
    static_configs:
      - targets: ['a1-mediator:10020']
    metrics_path: /a1-p/metrics
    scrape_interval: 30s

  # xApps
  - job_name: 'xapps'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - oran-nearrt-ric
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_component]
        action: keep
        regex: xapp
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - source_labels: [__meta_kubernetes_pod_label_oran_org_rrm_task]
        action: replace
        target_label: rrm_task
    metrics_path: /metrics
    scrape_interval: 15s  # Higher frequency for xApp performance monitoring

  # SMO Mock
  - job_name: 'smo-mock'
    static_configs:
      - targets: ['smo-mock:8080']
    metrics_path: /metrics
    scrape_interval: 30s

  # Redis (for A1 Mediator and FL Coordinator)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
    scrape_interval: 30s

  # PostgreSQL (for FL Coordinator)
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: /metrics
    scrape_interval: 30s

  # Node Exporter (for system metrics)
  - job_name: 'node-exporter'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: node-exporter
      - source_labels: [__meta_kubernetes_pod_node_name]
        action: replace
        target_label: instance
    metrics_path: /metrics
    scrape_interval: 30s

  # cAdvisor (for container metrics)
  - job_name: 'cadvisor'
    kubernetes_sd_configs:
      - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
    metrics_path: /metrics
    scrape_interval: 30s

  # kube-state-metrics (for Kubernetes object metrics)
  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['kube-state-metrics:8080']
    metrics_path: /metrics
    scrape_interval: 30s

# Remote write configuration (for long-term storage)
remote_write:
  - url: "http://prometheus-remote-storage:9201/write"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500

# Remote read configuration (for long-term storage)
remote_read:
  - url: "http://prometheus-remote-storage:9201/read"