# Pod Security Standards for O-RAN Near-RT RIC
apiVersion: v1
kind: Namespace
metadata:
  name: oran-nearrt-ric
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    name: oran-nearrt-ric
---
# Security Context Constraints for OpenShift compatibility
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: oran-restricted-scc
  labels:
    app.kubernetes.io/name: oran-nearrt-ric
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowPrivilegeEscalation: false
allowedCapabilities: null
defaultAddCapabilities: null
requiredDropCapabilities:
- ALL
fsGroup:
  type: RunAsAny
readOnlyRootFilesystem: true
runAsUser:
  type: MustRunAsNonRoot
seLinuxContext:
  type: MustRunAs
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
---
# RBAC for Pod Security
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: oran-nearrt-ric
  name: pod-security-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-security-reader-binding
  namespace: oran-nearrt-ric
subjects:
- kind: ServiceAccount
  name: fl-coordinator
  namespace: oran-nearrt-ric
- kind: ServiceAccount
  name: dashboard
  namespace: oran-nearrt-ric
roleRef:
  kind: Role
  name: pod-security-reader
  apiGroup: rbac.authorization.k8s.io