// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: src/app/backend/federatedlearning/proto/federatedlearning.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientRegistration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	XappName string   `protobuf:"bytes,1,opt,name=xapp_name,json=xappName,proto3" json:"xapp_name,omitempty"`
	Endpoint string   `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	RrmTasks []string `protobuf:"bytes,3,rep,name=rrm_tasks,json=rrmTasks,proto3" json:"rrm_tasks,omitempty"`
}

func (x *ClientRegistration) Reset() {
	*x = ClientRegistration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRegistration) ProtoMessage() {}

func (x *ClientRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRegistration.ProtoReflect.Descriptor instead.
func (*ClientRegistration) Descriptor() ([]byte, []int) {
	return file_src_app_backend_federatedlearning_proto_federatedlearning_proto_rawDescGZIP(), []int{0}
}

func (x *ClientRegistration) GetXappName() string {
	if x != nil {
		return x.XappName
	}
	return ""
}

func (x *ClientRegistration) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ClientRegistration) GetRrmTasks() []string {
	if x != nil {
		return x.RrmTasks
	}
	return nil
}

type ModelUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId         string        `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ModelId          string        `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Round            int64         `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	Parameters       []byte        `protobuf:"bytes,4,opt,name=parameters,proto3" json:"parameters,omitempty"`
	ParametersHash   string        `protobuf:"bytes,5,opt,name=parameters_hash,json=parametersHash,proto3" json:"parameters_hash,omitempty"`
	DataSamplesCount int64         `protobuf:"varint,6,opt,name=data_samples_count,json=dataSamplesCount,proto3" json:"data_samples_count,omitempty"`
	LocalMetrics     *ModelMetrics `protobuf:"bytes,7,opt,name=local_metrics,json=localMetrics,proto3" json:"local_metrics,omitempty"`
}

func (x *ModelUpdate) Reset() {
	*x = ModelUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelUpdate) ProtoMessage() {}

func (x *ModelUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelUpdate.ProtoReflect.Descriptor instead.
func (*ModelUpdate) Descriptor() ([]byte, []int) {
	return file_src_app_backend_federatedlearning_proto_federatedlearning_proto_rawDescGZIP(), []int{1}
}

func (x *ModelUpdate) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ModelUpdate) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelUpdate) GetRound() int64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *ModelUpdate) GetParameters() []byte {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ModelUpdate) GetParametersHash() string {
	if x != nil {
		return x.ParametersHash
	}
	return ""
}

func (x *ModelUpdate) GetDataSamplesCount() int64 {
	if x != nil {
		return x.DataSamplesCount
	}
	return 0
}

func (x *ModelUpdate) GetLocalMetrics() *ModelMetrics {
	if x != nil {
		return x.LocalMetrics
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_src_app_backend_federatedlearning_proto_federatedlearning_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type ServerChallenge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce []byte `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *ServerChallenge) Reset() {
	*x = ServerChallenge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerChallenge) ProtoMessage() {}

func (x *ServerChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerChallenge.ProtoReflect.Descriptor instead.
func (*ServerChallenge) Descriptor() ([]byte, []int) {
	return file_src_app_backend_federatedlearning_proto_federatedlearning_proto_rawDescGZIP(), []int{3}
}

func (x *ServerChallenge) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type ModelConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModelId    string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Round      int64                  `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Parameters []byte                 `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Config     *TrainingConfiguration `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *ModelConfiguration) Reset() {
	*x = ModelConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelConfiguration) ProtoMessage() {}

func (x *ModelConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelConfiguration.ProtoReflect.Descriptor instead.
func (*ModelConfiguration) Descriptor() ([]byte, []int) {
	return file_src_app_backend_federatedlearning_proto_federatedlearning_proto_rawDescGZIP(), []int{4}
}

func (x *ModelConfiguration) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelConfiguration) GetRound() int64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *ModelConfiguration) GetParameters() []byte {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ModelConfiguration) GetConfig() *TrainingConfiguration {
	if x != nil {
		return x.Config
	}
	return nil
}

type RoundResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModelId string        `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Round   int64         `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Metrics *ModelMetrics `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
}

func (x *RoundResult) Reset() {
	*x = RoundResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoundResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundResult) ProtoMessage() {}

func (x *RoundResult) ProtoReflect() protoreflect.Message {
	mi := &file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundResult.ProtoReflect.Descriptor instead.
func (*RoundResult) Descriptor() ([]byte, []int) {
	return file_src_app_backend_federatedlearning_proto_federatedlearning_proto_rawDescGZIP(), []int{5}
}

func (x *RoundResult) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *RoundResult) GetRound() int64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *RoundResult) GetMetrics() *ModelMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type ModelMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accuracy float64 `protobuf:"fixed64,1,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Loss     float64 `protobuf:"fixed64,2,opt,name=loss,proto3" json:"loss,omitempty"`
}

func (x *ModelMetrics) Reset() {
	*x = ModelMetrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelMetrics) ProtoMessage() {}

func (x *ModelMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelMetrics.ProtoReflect.Descriptor instead.
func (*ModelMetrics) Descriptor() ([]byte, []int) {
	return file_src_app_backend_federatedlearning_proto_federatedlearning_proto_rawDescGZIP(), []int{6}
}

func (x *ModelMetrics) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *ModelMetrics) GetLoss() float64 {
	if x != nil {
		return x.Loss
	}
	return 0
}

type TrainingConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BatchSize   int32   `protobuf:"varint,1,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	LocalEpochs int32   `protobuf:"varint,2,opt,name=local_epochs,json=localEpochs,proto3" json:"local_epochs,omitempty"`
	LearningRate float64 `protobuf:"fixed64,3,opt,name=learning_rate,json=learningRate,proto3" json:"learning_rate,omitempty"`
}

func (x *TrainingConfiguration) Reset() {
	*x = TrainingConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainingConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingConfiguration) ProtoMessage() {}

func (x *TrainingConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingConfiguration.ProtoReflect.Descriptor instead.
func (*TrainingConfiguration) Descriptor() ([]byte, []int) {
	return file_src_app_backend_federatedlearning_proto_federatedlearning_proto_rawDescGZIP(), []int{7}
}

func (x *TrainingConfiguration) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *TrainingConfiguration) GetLocalEpochs() int32 {
	if x != nil {
		return x.LocalEpochs
	}
	return 0
}

func (x *TrainingConfiguration) GetLearningRate() float64 {
	if x != nil {
		return x.LearningRate
	}
	return 0
}

type TrainingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*TrainingRequest_Registration
	//	*TrainingRequest_Update
	//	*TrainingRequest_Heartbeat
	Request isTrainingRequest_Request `protobuf_oneof:"request"`
}

func (x *TrainingRequest) Reset() {
	*x = TrainingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingRequest) ProtoMessage() {}

func (x *TrainingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingRequest.ProtoReflect.Descriptor instead.
func (*TrainingRequest) Descriptor() ([]byte, []int) {
	return file_src_app_backend_federatedlearning_proto_federatedlearning_proto_rawDescGZIP(), []int{8}
}

func (m *TrainingRequest) GetRequest() isTrainingRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *TrainingRequest) GetRegistration() *ClientRegistration {
	if x, ok := x.GetRequest().(*TrainingRequest_Registration); ok {
		return x.Registration
	}
	return nil
}

func (x *TrainingRequest) GetUpdate() *ModelUpdate {
	if x, ok := x.GetRequest().(*TrainingRequest_Update); ok {
		return x.Update
	}
	return nil
}

func (x *TrainingRequest) GetHeartbeat() *Heartbeat {
	if x, ok := x.GetRequest().(*TrainingRequest_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

type isTrainingRequest_Request interface {
	isTrainingRequest_Request()
}

type TrainingRequest_Registration struct {
	Registration *ClientRegistration `protobuf:"bytes,1,opt,name=registration,proto3,oneof"`
}

type TrainingRequest_Update struct {
	Update *ModelUpdate `protobuf:"bytes,2,opt,name=update,proto3,oneof"`
}

type TrainingRequest_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

func (*TrainingRequest_Registration) isTrainingRequest_Request() {}

func (*TrainingRequest_Update) isTrainingRequest_Request() {}

func (*TrainingRequest_Heartbeat) isTrainingRequest_Request() {}

type TrainingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*TrainingResponse_Challenge
	//	*TrainingResponse_Config
	//	*TrainingResponse_Result
	Response isTrainingResponse_Response `protobuf_oneof:"response"`
}

func (x *TrainingResponse) Reset() {
	*x = TrainingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingResponse) ProtoMessage() {}

func (x *TrainingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingResponse.ProtoReflect.Descriptor instead.
func (*TrainingResponse) Descriptor() ([]byte, []int) {
	return file_src_app_backend_federatedlearning_proto_federatedlearning_proto_rawDescGZIP(), []int{9}
}

func (m *TrainingResponse) GetResponse() isTrainingResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *TrainingResponse) GetChallenge() *ServerChallenge {
	if x, ok := x.GetResponse().(*TrainingResponse_Challenge); ok {
		return x.Challenge
	}
	return nil
}

func (x *TrainingResponse) GetConfig() *ModelConfiguration {
	if x, ok := x.GetResponse().(*TrainingResponse_Config); ok {
		return x.Config
	}
	return nil
}

func (x *TrainingResponse) GetResult() *RoundResult {
	if x, ok := x.GetResponse().(*TrainingResponse_Result); ok {
		return x.Result
	}
	return nil
}

type isTrainingResponse_Response interface {
	isTrainingResponse_Response()
}

type TrainingResponse_Challenge struct {
	Challenge *ServerChallenge `protobuf:"bytes,1,opt,name=challenge,proto3,oneof"`
}

type TrainingResponse_Config struct {
	Config *ModelConfiguration `protobuf:"bytes,2,opt,name=config,proto3,oneof"`
}

type TrainingResponse_Result struct {
	Result *RoundResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

func (*TrainingResponse_Challenge) isTrainingResponse_Response() {}

func (*TrainingResponse_Config) isTrainingResponse_Response() {}

func (*TrainingResponse_Result) isTrainingResponse_Response() {}

var File_src_app_backend_federatedlearning_proto_federatedlearning_proto protoreflect.FileDescriptor

var file_src_app_backend_federatedlearning_proto_federatedlearning_proto_rawDesc = []byte{
	0x0a, 0x41, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x2f, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x6c, 0x65, 0x61, 0x72, 0x6e,
	0x69, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x64, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x11, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x6c, 0x65, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x22, 0x6e, 0x0a, 0x12, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x78, 0x61,
	0x70, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x78,
	0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x72, 0x6d, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x72, 0x72, 0x6d, 0x54, 0x61, 0x73, 0x6b, 0x73,
	0x22, 0x9d, 0x02, 0x0a, 0x0b, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x27,
	0x0a, 0x0f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x5f, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x48, 0x61, 0x73, 0x68, 0x12, 0x2c, 0x0a, 0x12, 0x64, 0x61, 0x74, 0x61, 0x5f,
	0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x10, 0x64, 0x61, 0x74, 0x61, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x44, 0x0a, 0x0d, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x6d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x66,
	0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67,
	0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x0c, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x22, 0x28, 0x0a, 0x09, 0x48,
	0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x27, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43,
	0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0xb3,
	0x01, 0x0a, 0x12, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x46, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x64, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e,
	0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x7f, 0x0a, 0x0b, 0x52, 0x6f, 0x75, 0x6e,
	0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x3f, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x66, 0x65, 0x64, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x64, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x22, 0x3e, 0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x61, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x6c,
	0x6f, 0x73, 0x73, 0x22, 0x7e, 0x0a, 0x15, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a,
	0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x62, 0x61, 0x74, 0x63, 0x68, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x73, 0x12, 0x23,
	0x0a, 0x0d, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x52,
	0x61, 0x74, 0x65, 0x22, 0xe1, 0x01, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4f, 0x0a, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e,
	0x67, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64,
	0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x3a,
	0x0a, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x6c, 0x65, 0x61,
	0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x48,
	0x00, 0x52, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x42, 0x09, 0x0a, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xe1, 0x01, 0x0a, 0x10, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x09,
	0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x6c, 0x65, 0x61, 0x72, 0x6e,
	0x69, 0x6e, 0x67, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65,
	0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65,
	0x12, 0x3f, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x25, 0x2e, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x6c, 0x65, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x38, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x6c, 0x65, 0x61,
	0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x0a, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x7c, 0x0a, 0x11, 0x46, 0x65, 0x64, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x64, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x67, 0x0a, 0x0e,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x22,
	0x2e, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69,
	0x6e, 0x67, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x23, 0x2e, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x6c, 0x65,
	0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x39, 0x5a,
	0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x75, 0x62, 0x65,
	0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x2f, 0x64, 0x61, 0x73, 0x68, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x2f, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2f, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69,
	0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_app_backend_federatedlearning_proto_federatedlearning_proto_rawDescOnce sync.Once
	file_src_app_backend_federatedlearning_proto_federatedlearning_proto_rawDescData = file_src_app_backend_federatedlearning_proto_federatedlearning_proto_rawDesc
)

func file_src_app_backend_federatedlearning_proto_federatedlearning_proto_rawDescGZIP() []byte {
	file_src_app_backend_federatedlearning_proto_federatedlearning_proto_rawDescOnce.Do(func() {
		file_src_app_backend_federatedlearning_proto_federatedlearning_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_app_backend_federatedlearning_proto_federatedlearning_proto_rawDescData)
	})
	return file_src_app_backend_federatedlearning_proto_federatedlearning_proto_rawDescData
}

var file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_src_app_backend_federatedlearning_proto_federatedlearning_proto_goTypes = []interface{}{
	(*ClientRegistration)(nil),    // 0: federatedlearning.ClientRegistration
	(*ModelUpdate)(nil),           // 1: federatedlearning.ModelUpdate
	(*Heartbeat)(nil),             // 2: federatedlearning.Heartbeat
	(*ServerChallenge)(nil),       // 3: federatedlearning.ServerChallenge
	(*ModelConfiguration)(nil),    // 4: federatedlearning.ModelConfiguration
	(*RoundResult)(nil),           // 5: federatedlearning.RoundResult
	(*ModelMetrics)(nil),          // 6: federatedlearning.ModelMetrics
	(*TrainingConfiguration)(nil), // 7: federatedlearning.TrainingConfiguration
	(*TrainingRequest)(nil),       // 8: federatedlearning.TrainingRequest
	(*TrainingResponse)(nil),      // 9: federatedlearning.TrainingResponse
}
var file_src_app_backend_federatedlearning_proto_federatedlearning_proto_depIdxs = []int32{
	6,  // 0: federatedlearning.ModelUpdate.local_metrics:type_name -> federatedlearning.ModelMetrics
	7,  // 1: federatedlearning.ModelConfiguration.config:type_name -> federatedlearning.TrainingConfiguration
	6,  // 2: federatedlearning.RoundResult.metrics:type_name -> federatedlearning.ModelMetrics
	0,  // 3: federatedlearning.TrainingRequest.registration:type_name -> federatedlearning.ClientRegistration
	1,  // 4: federatedlearning.TrainingRequest.update:type_name -> federatedlearning.ModelUpdate
	2,  // 5: federatedlearning.TrainingRequest.heartbeat:type_name -> federatedlearning.Heartbeat
	3,  // 6: federatedlearning.TrainingResponse.challenge:type_name -> federatedlearning.ServerChallenge
	4,  // 7: federatedlearning.TrainingResponse.config:type_name -> federatedlearning.ModelConfiguration
	5,  // 8: federatedlearning.TrainingResponse.result:type_name -> federatedlearning.RoundResult
	8,  // 9: federatedlearning.FederatedLearning.HandleTraining:input_type -> federatedlearning.TrainingRequest
	9,  // 10: federatedlearning.FederatedLearning.HandleTraining:output_type -> federatedlearning.TrainingResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_src_app_backend_federatedlearning_proto_federatedlearning_proto_init() }
func file_src_app_backend_federatedlearning_proto_federatedlearning_proto_init() {
	if File_src_app_backend_federatedlearning_proto_federatedlearning_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientRegistration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Heartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerChallenge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoundResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelMetrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainingConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*TrainingRequest_Registration)(nil),
		(*TrainingRequest_Update)(nil),
		(*TrainingRequest_Heartbeat)(nil),
	}
	file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*TrainingResponse_Challenge)(nil),
		(*TrainingResponse_Config)(nil),
		(*TrainingResponse_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_app_backend_federatedlearning_proto_federatedlearning_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_app_backend_federatedlearning_proto_federatedlearning_proto_goTypes,
		DependencyIndexes: file_src_app_backend_federatedlearning_proto_federatedlearning_proto_depIdxs,
		MessageInfos:      file_src_app_backend_federatedlearning_proto_federatedlearning_proto_msgTypes,
	}.Build()
	File_src_app_backend_federatedlearning_proto_federatedlearning_proto = out.File
	file_src_app_backend_federatedlearning_proto_federatedlearning_proto_rawDesc = nil
	file_src_app_backend_federatedlearning_proto_federatedlearning_proto_goTypes = nil
	file_src_app_backend_federatedlearning_proto_federatedlearning_proto_depIdxs = nil
}
