{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "oran-nearrt-ric.fullname" . }}
  labels:
    {{- include "oran-nearrt-ric.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "oran-nearrt-ric.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "oran-nearrt-ric.selectorLabels" . | nindent 10 }}
    ports:
    - port: 80
    - port: 443
    - port: 8080
    - port: 4200
    - port: 36421
      protocol: SCTP
    - port: 10020
    - port: 830
  egress:
  - to:
    - podSelector:
        matchLabels:
          {{- include "oran-nearrt-ric.selectorLabels" . | nindent 10 }}
  - to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - port: 53
      protocol: UDP
{{- end }}