{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oran-nearrt-ric.serviceAccountName" . }}
  namespace: {{ include "oran-nearrt-ric.namespace" . }}
  labels:
    {{- include "oran-nearrt-ric.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}