# Main Dashboard Service
{{- if .Values.mainDashboard.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oran-nearrt-ric.fullname" . }}-main-dashboard
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oran-nearrt-ric.labels" . | nindent 4 }}
    app.kubernetes.io/component: main-dashboard
spec:
  type: {{ .Values.mainDashboard.service.type }}
  ports:
    - port: {{ .Values.mainDashboard.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "oran-nearrt-ric.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: main-dashboard
{{- end }}

---
# xApp Dashboard Service
{{- if .Values.xappDashboard.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oran-nearrt-ric.fullname" . }}-xapp-dashboard
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oran-nearrt-ric.labels" . | nindent 4 }}
    app.kubernetes.io/component: xapp-dashboard
spec:
  type: {{ .Values.xappDashboard.service.type }}
  ports:
    - port: {{ .Values.xappDashboard.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "oran-nearrt-ric.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: xapp-dashboard
{{- end }}
