# .github/workflows/deploy.yaml
name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.oran.local
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'
      - name: Configure Kubernetes
        if: ${{ secrets.KUBECONFIG_STAGING != '' }}
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG_STAGING }}
      - name: Deploy to staging
        if: ${{ secrets.KUBECONFIG_STAGING != '' }}
        env:
          KUBECONFIG_STAGING: ${{ secrets.KUBECONFIG_STAGING }}
        run: |
          if [ -f "Makefile" ]; then
            make deploy RELEASE_NAME=staging-release
          else
            echo "Makefile not found, skipping deployment"
          fi

  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run E2E tests
        run: |
          # Add commands to run E2E tests against the staging environment
          echo "Running E2E tests..."

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: e2e-tests
    environment:
      name: production
      url: https://oran.local
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'
      - name: Configure Kubernetes
        if: ${{ secrets.KUBECONFIG_PRODUCTION != '' }}
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG_PRODUCTION }}
      - name: Deploy to production
        if: ${{ secrets.KUBECONFIG_PRODUCTION != '' }}
        env:
          KUBECONFIG_PRODUCTION: ${{ secrets.KUBECONFIG_PRODUCTION }}
        run: |
          if [ -f "Makefile" ]; then
            make deploy RELEASE_NAME=production-release
          else
            echo "Makefile not found, skipping deployment"
          fi
      - name: Rollback on failure
        if: failure()
        run: helm rollback production-release
